services:
  ngcash:
    image: postgres
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=ng
volumes:
  pgdata: